### Dimensions

```
Scalar  ->  5              (just a number,      0D)
Vector  ->  [1 2 3]        (a line of numbers,  1D)
Matrix  ->  [[1 2]         (a table,            2D)
             [3 4]]
Tensor  ->  a stack of tables
```

A pandas **DataFrame is basically a matrix with names**



> did you know?? the name "pandas" does not come from the animal. it comes from PANel DAta System - a fancy name for data tables.

**Roadmap:**
1. Creating data (Series & DataFrame)
2. Reading & writing files
3. Selecting data (`loc`, `iloc`, conditions)
4. Summary functions & maps
5. Grouping & sorting
6. Data types & missing values
7. Renaming & combining
8. Practice exercises

## 1. Creating data
Pandas gives us **two things**:

- **DataFrame** - a full table, with rows and columns. Like an Excel sheet.
- **Series** - just **one column** of that table.

**Simple way to think:** a DataFrame is a table. A Series is one column of it.
Glue some Series together side by side -> you get a DataFrame.

### Creating a DataFrame

### From a dictionary

- **Dictionary -> DataFrame**
  - **Keys** become **column names**
  - **Values** become **column data** (lists, arrays, or Series)

In [25]:
import pandas as pd

# a datafram from a dictionary: keys become column names, values become the column data
flood = pd.DataFrame({
    'district': ['Sylhet', 'Feni', 'Kurigram', 'Noakhali'],
    'rain':     [320, 350, 280, 330],
    'families': [12000, 15200, 9800, 13100]
})
flood

   district  rain  families
0    Sylhet   320     12000
1      Feni   350     15200
2  Kurigram   280      9800
3  Noakhali   330     13100

See the `0, 1, 2, 3` on the left? Pandas numbers every row by itself.
That left side is called the **index**. We can put our own labels there instead:

In [26]:
pd.DataFrame(
    {'shelter': [45, 52],
     'volunteers': [340, 300]},
    index = ['Sylhet', 'Feni']
)

        shelter  volunteers
Sylhet       45         340
Feni         52         300

### From a list of lists

A DataFrame can also be made from a list of lists. Each inner list is **one row**

In [27]:
pd.DataFrame(
    [
        ['Sylhet', 320],
        ['Feni', 350],
        ['Kurigram', 280]
    ],
    columns=['district', 'rain'],   # column names
)

   district  rain
0    Sylhet   320
1      Feni   350
2  Kurigram   280

And one single column alone = a **Series**.
### from list

In [28]:
shelters = pd.Series([45, 52, 38], index=['Sylhet', 'Feni', 'Kurigram'])
shelters

Sylhet      45
Feni        52
Kurigram    38
dtype: int64

- **Dictionary -> Series**
  - **Keys** become the **index**
  - **Values** become the **data**

In [29]:
rainfall = {
    'Sylhet': 320,
    'Feni': 350,
    'Kurigram': 280,
    'Noakhali': 330
}

rain = pd.Series(rainfall)

rain

Sylhet      320
Feni        350
Kurigram    280
Noakhali    330
dtype: int64

more ways to make a Series from a **numpy array**:

In [30]:
import numpy as np

rain_arr = np.array([320, 410, 280])
pd.Series(rain_arr, index=['Sylhet', 'Sunamganj', 'Kurigram'])

Sylhet       320
Sunamganj    410
Kurigram     280
dtype: int64

**masking a Series** : write a True/False test inside `[ ]` and only the passing values stay:

In [31]:
shelters[shelters > 40]

Sylhet    45
Feni      52
dtype: int64

### task 1

1. Make a Series of **5 numbers** (relief trucks sent to 5 districts — invent the numbers).
2. Multiply every value by 10.
3. Keep only the values above 20.

In [32]:
# your code here:

## 2. Reading and saving files

nobody types data by hand in real work. data comes as a **file**-usually a **CSV** (comma seperated values)file.

for example, district office sends us this year's flood report. We'll make that file
once, then read it back — because reading files is how every real project starts.

In [33]:
report = pd.DataFrame({
    'district': ['Sylhet', 'Sunamganj', 'Kurigram', 'Feni',
                 'Netrokona', 'Lalmonirhat', 'Habiganj', 'Noakhali'],
    'division': ['Sylhet', 'Sylhet', 'Rangpur', 'Chattogram',
                 'Mymensingh', 'Rangpur', 'Sylhet', 'Chattogram'],
    'rain':     [320, 410, 280, 350, 290, 260, 300, 330],
    'water':    [850, 920, 780, 810, 760, None, 800, 790],  # water level; Lalmonirhat's meter broke!
    'families': [12000, 18500, 9800, 15200, 7600, 8900, 10400, 13100],
    'shelters': [45, 60, 38, 52, 30, 33, 41, 48]
})
report.to_csv('flood_report.csv', index=False) # save to a file
flood = pd.read_csv('flood_report.csv')         # read from a file
flood

      district    division  rain  water  families  shelters
0       Sylhet      Sylhet   320  850.0     12000        45
1    Sunamganj      Sylhet   410  920.0     18500        60
2     Kurigram     Rangpur   280  780.0      9800        38
3         Feni  Chattogram   350  810.0     15200        52
4    Netrokona  Mymensingh   290  760.0      7600        30
5  Lalmonirhat     Rangpur   260    NaN      8900        33
6     Habiganj      Sylhet   300  800.0     10400        41
7     Noakhali  Chattogram   330  790.0     13100        48

you can make any col as index col

`flood = pd.read_csv('flood_report.csv', index_col="district") `

whenever you get a new dataset, do these three checks first always

In [34]:
print(flood.shape) # (rows, columns)
flood.head(3) # first 3 rows

(8, 6)

    district division  rain  water  families  shelters
0     Sylhet   Sylhet   320  850.0     12000        45
1  Sunamganj   Sylhet   410  920.0     18500        60
2   Kurigram  Rangpur   280  780.0      9800        38

In [35]:
display(flood.tail(2))

   district    division  rain  water  families  shelters
6  Habiganj      Sylhet   300  800.0     10400        41
7  Noakhali  Chattogram   330  790.0     13100        48

In [36]:
# sample = random rows (nice for a quick unbiased look)
flood.sample(3)

      district    division  rain  water  families  shelters
5  Lalmonirhat     Rangpur   260    NaN      8900        33
7     Noakhali  Chattogram   330  790.0     13100        48
3         Feni  Chattogram   350  810.0     15200        52

In [37]:
flood.info() # col names, types and where data is missing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   district  8 non-null      object
 1   division  8 non-null      object
 2   rain      8 non-null      int64
 3   water     7 non-null      float64
 4   families  8 non-null      int64
 5   shelters  8 non-null      int64
dtypes: float64(1), int64(3), object(2)
memory usage: 516.0+ bytes

a few more quick **properties** (no brackets - they are values, not functions):

In [38]:
print(flood.columns)   # column names
print(flood.size)      #  rows x columns(total cells)
print(flood.ndim) # DataFrame is 2D, as it has rows and columns

Index(['district', 'division', 'rain', 'water', 'families', 'shelters'], dtype='object')
48
2

pandas reads other file types too - like **JSON** and **JSONL**:

- JSON: whole table in one json structure
- JSONL: one json object **per line** (very common for logs and big data)


CSV
* Tabular data
* Human-readable
* Similar to Excel


JSON
* Structured key-value data
* Common in APIs and web applications

JSONL
* One JSON object per line
* Common for logs, streaming data, and ML datasets

In [39]:
flood.to_csv('flood.csv', index=False)

In [40]:
flood.to_json('flood.json')
pd.read_json('flood.json').head(3)

    district division  rain  water  families  shelters
0     Sylhet   Sylhet   320  850.0     12000        45
1  Sunamganj   Sylhet   410  920.0     18500        60
2   Kurigram  Rangpur   280  780.0      9800        38

In [41]:
flood.to_json('flood.jsonl')
pd.read_json('flood.jsonl').head(3)

    district division  rain  water  families  shelters
0     Sylhet   Sylhet   320  850.0     12000        45
1  Sunamganj   Sylhet   410  920.0     18500        60
2   Kurigram  Rangpur   280  780.0      9800        38

### task 2

We just saved `flood.csv`. Now:

1. Read it into a variable `my_flood`.
2. Print its **shape**.
3. Show 2 **random** rows.

In [42]:
# your code here:

## 3. picking data from table
 the skills you will use every single dat. three ways:

 1. `take one column -> df['col']`

In [43]:
flood['district']

0         Sylhet
1      Sunamganj
2       Kurigram
3           Feni
4      Netrokona
5    Lalmonirhat
6       Habiganj
7       Noakhali
Name: district, dtype: object

2. pick by position(0, 1, 2...) -> `df.iloc[...]`

iloc integer location

In [44]:
flood.iloc[0]

district    Sylhet
division    Sylhet
rain           320
water        850.0
families     12000
shelters        45
Name: 0, dtype: object

3. pick by name -> `df.loc[...]`

loc mean location by label

`loc[rows, columns]`

In [45]:
flood.loc[:, ['district', 'families']]   # all rows, only these two columns

      district  families
0       Sylhet     12000
1    Sunamganj     18500
2     Kurigram      9800
3         Feni     15200
4    Netrokona      7600
5  Lalmonirhat      8900
6     Habiganj     10400
7     Noakhali     13100

In [46]:
# Selecting a single row
print(flood.loc[0])

# Selecting a single cell
display(flood.loc[0, 'rain'])
# Example 3: Selecting a range of rows (from index 1 to 3, inclusive) and all columns
display(flood.loc[1:3, :])
print(flood.loc[1:3, 'division':'families'])

# Selecting specific rows and specific columns
display(flood.loc[[0, 2, 5], ['district', 'families', 'shelters']])

district    Sylhet
division    Sylhet
rain           320
water        850.0
families     12000
shelters        45
Name: 0, dtype: object

np.int64(320)

    district    division  rain  water  families  shelters
1  Sunamganj      Sylhet   410  920.0     18500        60
2   Kurigram     Rangpur   280  780.0      9800        38
3       Feni  Chattogram   350  810.0     15200        52

     division  rain  water  families
1      Sylhet   410  920.0     18500
2     Rangpur   280  780.0      9800
3  Chattogram   350  810.0     15200

      district  families  shelters
0       Sylhet     12000        45
2     Kurigram      9800        38
5  Lalmonirhat      8900        33

**A trap everyone falls in once:** `iloc[0:3]` gives rows 0, 1, 2 - it stops before 3,
just like Python lists. But `loc[0:3]` gives rows 0, 1, 2 **and 3**. `loc` includes both ends.

## picking with condition - the best part

you can ask the table a question. write the condition inside [], and only the matching rows come back

In [47]:
flood[flood['rain']>300] # where did it rain heavily?

    district    division  rain  water  families  shelters
0     Sylhet      Sylhet   320  850.0     12000        45
1  Sunamganj      Sylhet   410  920.0     18500        60
3       Feni  Chattogram   350  810.0     15200        52
7   Noakhali  Chattogram   330  790.0     13100        48

In [48]:
# joining condition: &, |
# caveat: () are must
flood[(flood['division']=='Sylhet')&(flood['families']>11000)]

    district division  rain  water  families  shelters
0     Sylhet   Sylhet   320  850.0     12000        45
1  Sunamganj   Sylhet   410  920.0     18500        60

```
flood[
    (flood['district'] == 'Kurigram') |
    (flood['district'] == 'Lalmonirhat')
]
```
see below

In [49]:
flood[flood['district'].isin(['Kurigram', 'Lalmonirhat'])]

      district division  rain  water  families  shelters
2     Kurigram  Rangpur   280  780.0      9800        38
5  Lalmonirhat  Rangpur   260    NaN      8900        33



> "show me the districts with more than 10,000 affected families -
send help there first."

adding a new column, just use `=`

In [50]:
flood['help_sent'] = False # same value in every row
flood['per_shelter'] = flood['families'] / flood['shelters'] # made from other columns
flood.head(3)

    district division  rain  water  families  shelters  help_sent  per_shelter
0     Sylhet   Sylhet   320  850.0     12000        45      False   266.666667
1  Sunamganj   Sylhet   410  920.0     18500        60      False   308.333333
2   Kurigram  Rangpur   280  780.0      9800        38      False   257.894737

`per_shelter` tells us how crowded each shelter is;a brand new, useful fact
made from two columns we already had. This is most of what data work looks like.

### task 3

1. Add a column `aid_packets` = `families // 100`.
2. Show only the districts with more than 12000 affected families.

In [51]:
# your code here:

renaming and dropping columns

In [52]:
rename_rain = flood.rename(columns={'rain': 'rain_mm'}).head(2)

In [53]:
rename_rain

,district,division,rain_mm,water,families,shelters,help_sent,per_shelter
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333

In [54]:
drop_helpsent = flood.drop(columns=['help_sent']).head(2)
drop_helpsent

    district division  rain  water  families  shelters  per_shelter
0     Sylhet   Sylhet   320  850.0     12000        45   266.666667
1  Sunamganj   Sylhet   410  920.0     18500        60   308.333333

**careful:** `rename` and `drop` give back a **new** table ,the original stays the same.
Two ways to actually keep the change:

- `flood = flood.drop(columns=['help_sent'])` -> reassign (recommended)
- `flood.drop(columns=['help_sent'], inplace=True)` -> changes the table itself, returns nothing

## 4.quick summaries and changing values

In [55]:
flood['rain'].describe()

count      8.000000
mean     317.500000
std       47.132033
min      260.000000
25%      287.500000
50%      310.000000
75%      335.000000
max      410.000000
Name: rain, dtype: float64

In [56]:
print('avg rair:', flood['rain'].mean())
print('division:', flood['division'].unique())
flood['division'].value_counts()

avg rair: 317.5
division: ['Sylhet' 'Rangpur' 'Chattogram' 'Mymensingh']

division
Sylhet        3
Rangpur       2
Chattogram    2
Mymensingh    1
Name: count, dtype: int64

> **Did you know?** `value_counts()` might be the most typed line in all of data science.
> For any text column, the first question is always: "what's inside, and how many of each?"

### map -> chnage every value in a column at once

Take a value ->
Apply the function ->
Return the result

In [57]:
# how much above or below avg rain did each district get???
avg = flood['rain'].mean()
flood['rain'].map(lambda r: r - avg)

0     2.5
1    92.5
2   -37.5
3    32.5
4   -27.5
5   -57.5
6   -17.5
7    12.5
Name: rain, dtype: float64

lambda:
```python
def subtract_average(r):
    return r - avg

In [58]:
# apply() is the same idea but it can look at the whole row at once
def danger(row):
    return row['rain'] / 100 + row['families'] / 1000

flood.apply(danger, axis=1)   # axis=1 means go row by row

0    15.2
1    22.6
2    12.6
3    18.7
4    10.5
5    11.5
6    13.4
7    16.4
dtype: float64

**But for simple maths, don't bother with map/apply** just use the columns directly:

In [59]:
flood['rain']/100 + flood['families']/1000

0    15.2
1    22.6
2    12.6
3    18.7
4    10.5
5    11.5
6    13.4
7    16.4
dtype: float64

## 5. grouping and sorting
### groupby

I want the TOTAL affected families **per division** - one number for each division.

In [60]:
flood.groupby('division')['families'].sum()

division
Chattogram    28300
Mymensingh     7600
Rangpur       18700
Sylhet        40900
Name: families, dtype: int64

aggregate function = we are reducing a bunch of values into one

In [61]:
# several ans at once
flood.groupby('division')['rain'].agg(['min', 'max', 'mean'])

            min  max        mean
division
Chattogram  330  350  340.000000
Mymensingh  290  290  290.000000
Rangpur     260  280  270.000000
Sylhet      300  410  343.333333

In [62]:
flood.groupby('division')['shelters'].sum().reset_index()

     division  shelters
0  Chattogram       100
1  Mymensingh        30
2     Rangpur        71
3      Sylhet       146

In [63]:
flood

,district,division,rain,water,families,shelters,help_sent,per_shelter
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333
2,Kurigram,Rangpur,280,780.0,9800,38,False,257.894737
3,Feni,Chattogram,350,810.0,15200,52,False,292.307692
4,Netrokona,Mymensingh,290,760.0,7600,30,False,253.333333
5,Lalmonirhat,Rangpur,260,NaN,8900,33,False,269.696970
6,Habiganj,Sylhet,300,800.0,10400,41,False,253.658537
7,Noakhali,Chattogram,330,790.0,13100,48,False,272.916667

### sorting

if we sort by `families`, biggest first - which district comes on top?

In [64]:
flood.sort_values('families', ascending=False)

,district,division,rain,water,families,shelters,help_sent,per_shelter
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333
3,Feni,Chattogram,350,810.0,15200,52,False,292.307692
7,Noakhali,Chattogram,330,790.0,13100,48,False,272.916667
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667
6,Habiganj,Sylhet,300,800.0,10400,41,False,253.658537
2,Kurigram,Rangpur,280,780.0,9800,38,False,257.894737
5,Lalmonirhat,Rangpur,260,NaN,8900,33,False,269.696970
4,Netrokona,Mymensingh,290,760.0,7600,30,False,253.333333

Sunamganj is thhe worst hit district!

In [65]:
flood.sort_values(['division','rain']) #sort by divsion then rain inside each

,district,division,rain,water,families,shelters,help_sent,per_shelter
7,Noakhali,Chattogram,330,790.0,13100,48,False,272.916667
3,Feni,Chattogram,350,810.0,15200,52,False,292.307692
4,Netrokona,Mymensingh,290,760.0,7600,30,False,253.333333
5,Lalmonirhat,Rangpur,260,NaN,8900,33,False,269.696970
2,Kurigram,Rangpur,280,780.0,9800,38,False,257.894737
6,Habiganj,Sylhet,300,800.0,10400,41,False,253.658537
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333

### task 4

Find the **average rain per division**, sorted from highest to lowest. (One line is possible!)

In [66]:
# your code here:

## 6. fixing missing data

missing data shows up as a NaN, not a number.

In [67]:
flood.isnull()

,district,division,rain,water,families,shelters,help_sent,per_shelter
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False

In [68]:
flood[flood['water'].isnull()]

,district,division,rain,water,families,shelters,help_sent,per_shelter
5,Lalmonirhat,Rangpur,260,NaN,8900,33,False,269.69697

In [69]:
flood.loc[5, 'water']

np.float64(nan)

In [70]:
flood.dropna()

,district,division,rain,water,families,shelters,help_sent,per_shelter
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333
2,Kurigram,Rangpur,280,780.0,9800,38,False,257.894737
3,Feni,Chattogram,350,810.0,15200,52,False,292.307692
4,Netrokona,Mymensingh,290,760.0,7600,30,False,253.333333
6,Habiganj,Sylhet,300,800.0,10400,41,False,253.658537
7,Noakhali,Chattogram,330,790.0,13100,48,False,272.916667

cleaning data is said to be 80% of the job

## 7. joining tables

### Two ways to join

- **`pd.concat()`** - put tables **on top of each other** (same columns, more rows).
- **`pd.merge()`** - join two tables **side by side** using a common column(same entities, more columns).

In [71]:
# concat: two districts sent their report late, add them below
late = pd.DataFrame({
    'district': ['Bandarban', 'Chandpur'],
    'division': ['Chattogram', 'Chattogram'],
    'rain': [370, 340],
    'water': [700, 720],
    'families': [5400, 8800],
    'shelters': [21, 35],
    'help_sent': [False, False],
    'per_shelter': [257.1, 251.4]
})
all_districts = pd.concat([flood, late])#  ignore_index=True
all_districts.tail(4)

,district,division,rain,water,families,shelters,help_sent,per_shelter
6,Habiganj,Sylhet,300,800.0,10400,41,False,253.658537
7,Noakhali,Chattogram,330,790.0,13100,48,False,272.916667
0,Bandarban,Chattogram,370,700.0,5400,21,False,257.100000
1,Chandpur,Chattogram,340,720.0,8800,35,False,251.400000

In [72]:
# merge: a different table has the relief stock of each district — join them
stock = pd.DataFrame({
    'district':  ['Sylhet', 'Sunamganj', 'Kurigram', 'Feni'],
    'rice_tons': [120, 95, 80, 110],
    'volunteers': [340, 280, 210, 300]
})
pd.merge(flood, stock, on='district')

,district,division,rain,water,families,shelters,help_sent,per_shelter,rice_tons,volunteers
0,Sylhet,Sylhet,320,850.0,12000,45,False,266.666667,120,340
1,Sunamganj,Sylhet,410,920.0,18500,60,False,308.333333,95,280
2,Kurigram,Rangpur,280,780.0,9800,38,False,257.894737,80,210
3,Feni,Chattogram,350,810.0,15200,52,False,292.307692,110,300

## 8. Practice

Use the `flood` table. Try each one

1. Show the **district and shelters** of every district with rain above 300.
2. What is the **average water level in each division**?
3. Lalmonirhat's water level is missing - **fill it** with the average, into a new column `water_clean`.
4. Which **division has the most affected families in total**? (one line!)
5. Add a column `status`: `'severe'` if families > 12000, otherwise `'moderate'`.

In [73]:
# your code here

**DONE**
Your pocket cheat sheet:

* Load data: `pd.read_csv()`
* First look at the data: `.head()`, `.info()`, `.describe()`, `.shape`
* Select data: `df['col']`, `.loc[]`, `.iloc[]`, `df[condition]`
* Summarize data: `.mean()`, `.unique()`, `.value_counts()`
* Modify values: `.map()`, `.apply()`, or regular operations like `+, -, , /`
* Group and aggregate: `.groupby()`, `.sum()`, `.agg()`, `.reset_index()`
* Sort data: `.sort_values()`
* Clean data: `.isnull()`, `.fillna()`, `.dropna()`, `.replace()`
* Join datasets: `pd.concat()`, `pd.merge()`